language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7-dev"  # replace with 3.7 once this is available easily
  - "nightly"
  - "pypy"
  - "pypy3"
matrix:
  allow_failures:
    - python: "nightly"
script:
  - "python setup.py test"
deploy:
  provider: pypi
  server: https://test.pypi.org
  user: edgewall-org
  password:
    secure: "W86OIU/V9PbXdERXbR1vTOw/GvxoNyn5gt7n52TGqjI1BcklX1t31uPgBnf0wmlp/kY9vMbOYhuqUWpBhbMKMBY6zOuNnCV0H5vynZ/nWefSBK6Fqyl2zTsdLYfzUKAIPBldYcaiJMZ6eD++ujVsgWN6XglP7jYogqjJFxxNf6s="
  distributions: "sdist bdist_wheel"
  on:
    tags: true
    python: "3.6"
